env:
  global:
    - SWIFT_DOCKER_IMAGE=swiftlang/swift:nightly-5.3
jobs:
  include:
    - stage: Mac test
      os: osx
      osx_image: xcode11.5
      language: swift
      script:
        swift test
    - stage: Linux test
      os: linux
      language: generic
      services:
        - docker
      before_install:
        - docker pull $SWIFT_DOCKER_IMAGE
      script:
        - docker run -v `pwd`:/tmp/build -w /tmp/build $SWIFT_DOCKER_IMAGE swift test
